//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Test.HumanResources
{
    using Test.HumanResources.Mapper;
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Library.DesignPatterns.Behavioral.Observation;
    using Microsoft.Extensions.Caching.Memory;
    using Library.Interfaces;

    public sealed partial class PersonDetailsComponent
    {
        protected override async Task OnInitializedAsync()
        {
            // Call developer's method.
            await this.OnLoadAsync();
        }

        [Microsoft.AspNetCore.Components.Parameter]
        public System.Int64? EntityId { get; set; }

        [Microsoft.AspNetCore.Components.Parameter]
        public Microsoft.AspNetCore.Components.EventCallback<System.Int64?>? EntityIdChanged { get; set; }

        public async void SaveButton_OnClick()
        {
            if (DataContext.Id == default)
            {
                var @params = this.DataContext.ToInsertPerson();
                var cqParams = new Test.HumanResources.Dtos.InsertPersonCommand(@params);
                var cqResult = await this._commandProcessor.ExecuteAsync<Test.HumanResources.Dtos.InsertPersonCommand, Test.HumanResources.Dtos.InsertPersonCommandResult>(cqParams);
            }
            else
            {
                var @params = this.DataContext.ToUpdatePerson();
                var cqParams = new Test.HumanResources.Dtos.UpdatePersonCommand(@params);
                var cqResult = await this._commandProcessor.ExecuteAsync<Test.HumanResources.Dtos.UpdatePersonCommand, Test.HumanResources.Dtos.UpdatePersonCommandResult>(cqParams);
            }
        }

        public void BackButton_OnClick()
        {
            this._navigationManager.NavigateTo("/HumanResources/Person");
        }

        public PersonDetailsComponent()
        {
        }
    }
}