//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Test.HumanResources.Commands
{
    using Library.Cqrs.Models.Commands;
    using Test.HumanResources.Dtos;

    /// <summary>
    /// The parameter of DeletePersonCommand
    /// </summary>
    public sealed partial class DeletePersonCommandParameter : Library.Cqrs.Models.Commands.ICommand
    {
        public DeletePersonParams Params { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref = "DeletePersonCommandParameter"/> class.
        /// </summary>
        public DeletePersonCommandParameter(DeletePersonParams @params)
        {
            this.Params = @params;
        }
    }
}