//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Queries.HumanResources.Test
{
    using HanyCo.Infra.Cqrs;
    using Dtos.HumanResources.Test;
    
    
    /// <summary>
    /// The result of GetByIdPersonQuery
    /// </summary>
    public sealed partial class GetByIdPersonQueryResult : IQueryResult<GetByIdPersonResult>
    {
        
    public GetByIdPersonResult Result
    {
        get;
        
    }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetByIdPersonQueryResult"/> class.
        /// </summary>
        public GetByIdPersonQueryResult(GetByIdPersonResult result)
        {
            this.Result = result;
        }
    }
}
