#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dtos.HumanResources.Test
{
    using System;
    using HanyCo.Infra.Markers;
    
    
    /// <summary>
    /// The data transfer object of InsertPersonResult
    /// </summary>
    public sealed partial class InsertPersonResult : IDto
    {
        
        /// <summary>
        /// Auto-generated by Functionality Service.
        /// </summary>
    public Int64 Id
    {
        get;
        set;
    }
    }
}
#endregion
