//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Test.HumanResources.Commands
{
    using Library.Cqrs.Models.Commands;
    using Test.HumanResources.Dtos;

    /// <summary>
    /// The result of InsertPersonCommand
    /// </summary>
    public sealed partial class InsertPersonCommandResult : Library.Cqrs.Models.Commands.ICommandResult
    {
        public InsertPersonResult Result { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref = "InsertPersonCommandResult"/> class.
        /// </summary>
        public InsertPersonCommandResult(InsertPersonResult result)
        {
            this.Result = result;
        }
    }
}