#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dtos.HumanResources.Test
{
    using System;
    using HanyCo.Infra.Markers;
    
    
    /// <summary>
    /// The data transfer object of InsertPersonParams
    /// </summary>
    public sealed partial class InsertPersonParams : IDto
    {
        
    public String FirstName
    {
        get;
        set;
    }
        
    public String LastName
    {
        get;
        set;
    }
        
    public DateTime DateOfBirth
    {
        get;
        set;
    }
        
    public Int32 Height
    {
        get;
        set;
    }
    }
}
#endregion
