#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResources.Test
{
    using System;
    using HanyCo.Infra.Markers;
    using HumanResources.Test;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// The data transfer object of PersonViewModel
    /// </summary>
    public sealed partial class PersonViewModel : IDto
    {

    // TODO: Generated Code
    //public List<PersonDto>?> PeopleListDto
    public List<PersonDto?> PeopleListDto
    {
        get;
        set;
    }
        
    public PersonDto? PersonDetailsDto
    {
        get;
        set;
    }
    }
}
#endregion
