//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.HumanResources.Commands
{
    using Library.Cqrs.Models.Commands;
    using Test.HumanResources.Dtos;
    
    
    /// <summary>
    /// The parameter of UpdatePersonCommand
    /// </summary>
    public sealed partial class UpdatePersonCommandParameter : ICommand
    {
        
    public UpdatePersonParams Params
    {
        get;
        
    }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePersonCommandParameter"/> class.
        /// </summary>
        public UpdatePersonCommandParameter(UpdatePersonParams @params)
        {
            this.Params = @params;
        }
    }
}
