#nullable enable
#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanyCo.Infra.Designers.UI.Queries
{
    using HanyCo.Infra.Cqrs.Query;
    using System;
    using HanyCo.Infra.Dto;
    using System.Collections.Generic;
    using HanyCo.Infra.Domain.Data.Contexts;
    using HanyCo.Infra.Mapping;
    
    
    /// <summary>
    /// The parameter of GetDtosByModuleIdQuery
    /// </summary>
    public sealed partial class GetDtosByModuleIdQueryParameter : IQueryParameter<GetDtosByModuleIdQueryResult>
    {
        
        public Guid Id { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDtosByModuleIdQueryParameter"/> class.
        /// </summary>
        public GetDtosByModuleIdQueryParameter(Guid id)
        {
            this.Id = id;
        }
    }
    
    /// <summary>
    /// The result of GetDtosByModuleIdQuery
    /// </summary>
    public sealed partial class GetDtosByModuleIdQueryResult : IQueryResult<IEnumerable<DTODto>>
    {
        
        public IEnumerable<DTODto> Result { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDtosByModuleIdQueryResult"/> class.
        /// </summary>
        public GetDtosByModuleIdQueryResult(IEnumerable<DTODto> result)
        {
            this.Result = result;
        }
    }
    
    /// <summary>
    /// The handler of GetDtosByModuleIdQuery
    /// </summary>
    public sealed partial class GetDtosByModuleIdQueryHandler : IQueryHandler<GetDtosByModuleIdQueryParameter,  GetDtosByModuleIdQueryResult>
    {
        
        public InfraWriteDbContext WriteDbContext { get; }
        
        public IMapper Mapper { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDtosByModuleIdQueryHandler"/> class.
        /// </summary>
        public GetDtosByModuleIdQueryHandler(InfraWriteDbContext writeDbContext, IMapper mapper)
        {
            this.WriteDbContext = writeDbContext;
            this.Mapper = mapper;
        }
    }
}
namespace HanyCo.Infra.Dto
{
    using System;
    
    
    /// <summary>
    /// The data transfer object of 
    /// </summary>
    public sealed partial class DTODto
    {
        
        [Mapping("Guid")]
        public Guid Id { get; set; }
        
        public String Name { get; set; }
    }
}
#endregion
