#nullable enable
#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanyCo.Infra.Designers.UI.Queries
{
    using HanyCo.Infra.Cqrs.Query;
    using System;
    using HanyCo.Infra.Dto;
    using HanyCo.Infra.Domain.Data.Contexts;
    using HanyCo.Infra.Mapping;
    
    
    /// <summary>
    /// The parameter of GetDtoByIdQuery
    /// </summary>
    public sealed partial class GetDtoByIdQueryParameter : IQueryParameter<GetDtoByIdQueryResult>
    {
        
        public Guid Id { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDtoByIdQueryParameter"/> class.
        /// </summary>
        public GetDtoByIdQueryParameter(Guid id)
        {
            this.Id = id;
        }
    }
    
    /// <summary>
    /// The result of GetDtoByIdQuery
    /// </summary>
    public sealed partial class GetDtoByIdQueryResult : IQueryResult<DTODto>
    {
        
        public DTODto Result { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDtoByIdQueryResult"/> class.
        /// </summary>
        public GetDtoByIdQueryResult(DTODto result)
        {
            this.Result = result;
        }
    }
    
    /// <summary>
    /// The handler of GetDtoByIdQuery
    /// </summary>
    public sealed partial class GetDtoByIdQueryHandler : IQueryHandler<GetDtoByIdQueryParameter,  GetDtoByIdQueryResult>
    {
        
        public InfraWriteDbContext WriteDbContext { get; }
        
        public IMapper Mapper { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetDtoByIdQueryHandler"/> class.
        /// </summary>
        public GetDtoByIdQueryHandler(InfraWriteDbContext writeDbContext, IMapper mapper)
        {
            this.WriteDbContext = writeDbContext;
            this.Mapper = mapper;
        }
    }
}
#endregion
