#nullable enable
#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanyCo.Infra.Designers.UI.Queries
{
    using HanyCo.Infra.Cqrs.Query;
    using System;
    using HanyCo.Infra.Dto;
    using HanyCo.Infra.Domain.Data.Contexts;
    using HanyCo.Infra.Mapping;
    
    
    /// <summary>
    /// The parameter of GetModuleByIdQuery
    /// </summary>
    public sealed partial class GetModuleByIdQueryParameter : IQueryParameter<GetModuleByIdQueryResult>
    {
        
        public Guid Id { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetModuleByIdQueryParameter"/> class.
        /// </summary>
        public GetModuleByIdQueryParameter(Guid id)
        {
            this.Id = id;
        }
    }
    
    /// <summary>
    /// The result of GetModuleByIdQuery
    /// </summary>
    public sealed partial class GetModuleByIdQueryResult : IQueryResult<ModuleDto>
    {
        
        public ModuleDto Result { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetModuleByIdQueryResult"/> class.
        /// </summary>
        public GetModuleByIdQueryResult(ModuleDto result)
        {
            this.Result = result;
        }
    }
    
    /// <summary>
    /// The handler of GetModuleByIdQuery
    /// </summary>
    public sealed partial class GetModuleByIdQueryHandler : IQueryHandler<GetModuleByIdQueryParameter,  GetModuleByIdQueryResult>
    {
        
        public InfraWriteDbContext WriteDbContext { get; }
        
        public IMapper Mapper { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetModuleByIdQueryHandler"/> class.
        /// </summary>
        public GetModuleByIdQueryHandler(InfraWriteDbContext writeDbContext, IMapper mapper)
        {
            this.WriteDbContext = writeDbContext;
            this.Mapper = mapper;
        }
    }
}
#endregion
