//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace HumanResources
{
    using Web.UI.Components.Shared;
    using HumanResources.Queries;
    using HumanResources.Dtos;
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Library.DesignPatterns.Behavioral.Observation;
    using Microsoft.Extensions.Caching.Memory;
    using Library.Interfaces;

    public sealed partial class PeopleListComponent
    {
        public PeopleListComponent()
        {
        }

        public void NewButton_OnClick()
        {
            
        }

        public void EditButton_OnClick(Int64 id)
        {
            
        }

        public async void DeleteButton_OnClick(Int64 id)
        {
            
        }

        protected override async Task OnInitializedAsync()
        {
            
        }

        public Web.UI.Components.Shared.MessageComponent MessageComponent { get; set; }
    }
}