#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Hr.Queries
{
    using HanyCo.Infra.Cqrs;
    using Test.Hr.Dtos;
    
    
    /// <summary>
    /// The parameter of GetByIdPersonQuery
    /// </summary>
    public sealed partial class GetByIdPersonQueryParameter : IQueryParameter<GetByIdPersonQueryResult>
    {
        
    public GetByIdPersonParams Params
    {
        get;
        
    }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetByIdPersonQueryParameter"/> class.
        /// </summary>
        public GetByIdPersonQueryParameter(GetByIdPersonParams @params)
        {
            this.Params = @params;
        }
    }
}
#endregion
