#nullable enable
#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanyCo.Infra.Designers.UI.Commands
{
    using HanyCo.Infra.Cqrs.Command;
    using HanyCo.Infra.Dto;
    using System;
    using HanyCo.Infra.Mapping;
    
    
    /// <summary>
    /// The parameter of CreateFormCommand
    /// </summary>
    public sealed partial class CreateFormCommandParameter : ICommandParameter
    {
        
        public FormDto Dto { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateFormCommandParameter"/> class.
        /// </summary>
        public CreateFormCommandParameter(FormDto dto)
        {
            this.Dto = dto;
        }
    }
    
    /// <summary>
    /// The result of CreateFormCommand
    /// </summary>
    public sealed partial class CreateFormCommandResult : ICommandResult
    {
        
        public Guid Result { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateFormCommandResult"/> class.
        /// </summary>
        public CreateFormCommandResult(Guid result)
        {
            this.Result = result;
        }
    }
    
    /// <summary>
    /// The handler of CreateFormCommand
    /// </summary>
    public sealed partial class CreateFormCommandHandler : ICommandHandler<CreateFormCommandParameter,  CreateFormCommandResult>
    {
        
        public IMapper Mapper { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateFormCommandHandler"/> class.
        /// </summary>
        public CreateFormCommandHandler(IMapper mapper)
        {
            this.Mapper = mapper;
        }
    }
}
namespace HanyCo.Infra.Dto
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// The data transfer object of Form
    /// </summary>
    public sealed partial class FormDto
    {
        
        public String FormFullName { get; set; }
        
        public String FormTemplate { get; set; }
        
        public String Route { get; set; }
        
        public Int64 ModuleId { get; set; }
        
        public IEnumerable<Int64> DtoIds { get; set; }
    }
}
#endregion
