#nullable enable
#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanyCo.Infra.Designers.UI.Commands
{
    using HanyCo.Infra.Cqrs.Command;
    using System;
    using HanyCo.Infra.Dto;
    using HanyCo.Infra.Mapping;
    
    
    /// <summary>
    /// The parameter of UpdateFormCommand
    /// </summary>
    public sealed partial class UpdateFormCommandParameter : ICommandParameter
    {
        
        public Guid Id { get; }
        
        public FormDto Dto { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateFormCommandParameter"/> class.
        /// </summary>
        public UpdateFormCommandParameter(Guid id, FormDto dto)
        {
            this.Id = id;
            this.Dto = dto;
        }
    }
    
    /// <summary>
    /// The result of UpdateFormCommand
    /// </summary>
    public sealed partial class UpdateFormCommandResult : ICommandResult
    {
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateFormCommandResult"/> class.
        /// </summary>
        public UpdateFormCommandResult()
        {
        }
    }
    
    /// <summary>
    /// The handler of UpdateFormCommand
    /// </summary>
    public sealed partial class UpdateFormCommandHandler : ICommandHandler<UpdateFormCommandParameter,  UpdateFormCommandResult>
    {
        
        public IMapper Mapper { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateFormCommandHandler"/> class.
        /// </summary>
        public UpdateFormCommandHandler(IMapper mapper)
        {
            this.Mapper = mapper;
        }
    }
}
#endregion
