//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace HumanResources
{
    using HumanResources.Mapper;
    using HumanResources.Queries;
    using HumanResources.Dtos;
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Library.DesignPatterns.Behavioral.Observation;
    using Microsoft.Extensions.Caching.Memory;
    using Library.Interfaces;

    public sealed partial class PeopleListComponent
    {
        public PeopleListComponent()
        {
        }

        public void NewButton_OnClick()
        {
            this._navigationManager.NavigateTo("/HumanResources/Person/details");
        }

        public void EditButton_OnClick(Int64 id)
        {
            this._navigationManager.NavigateTo($"/HumanResources/Person/details/{id.ToString()}");
        }

        public async void DeleteButton_OnClick(Int64 id)
        {
            // Setup segregation parameters
            var cmdParams = new HumanResources.Dtos.DeletePerson()
            {
                Id = id,
            };
            var cmd = new HumanResources.Dtos.DeletePersonCommand(cmdParams);
            // Invoke the command handler to apply changes.
            var cqResult = await this._commandProcessor.ExecuteAsync<HumanResources.Dtos.DeletePersonCommand, HumanResources.Dtos.DeletePersonCommandResult>(cmd);
            // Now, set let UI know that the state is changed
            await OnInitializedAsync();
            MessageComponent.Show("Delete Entity", "Entity deleted.");
            this.StateHasChanged();
        }

        protected override async Task OnInitializedAsync()
        {
            // Setup segregation parameters
            var @params = new HumanResources.Dtos.GetAllPeople();
            var cqParams = new HumanResources.Dtos.GetAllPeopleQuery(@params);
            // Invoke the query handler to retrieve all entities
            var cqResult = await this._queryProcessor.ExecuteAsync<HumanResources.Dtos.GetAllPeopleQueryResult>(cqParams);
            // Now, set the data context.
            this.DataContext = cqResult.Result.ToViewModel();
            // Call developer's method.
            await this.OnLoadAsync();
        }

        public BlazorApp.Shared.MessageComponent MessageComponent { get; set; }
    }
}