//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.HumanResources
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Library.DesignPatterns.Behavioral.Observation;
    using Microsoft.Extensions.Caching.Memory;
    using Library.Interfaces;
    using Test.HumanResources.Dtos;

    public sealed partial class PersonDetailsComponent
    {
        
        public async void SaveButton_OnClick()
        {
            //this.ValidateForm();
            //var dto = this.DataContext;
            //var cqParams = new Test.HumanResources.Dtos.InsertPersonParams(dto);
            //OnInsertPersonCommandCalling(cqParams);

            //var cqResult = await this._commandProcessor.ExecuteAsync<Test.HumanResources.Dtos.InsertPersonParams,Test.HumanResources.Dtos.InsertPersonResult>(cqParams);

            //OnInsertPersonCommandCalled(cqParams, cqResult);

            this.ValidateForm();
            var viewModel = this.DataContext;
            var @params = new Test.HumanResources.Dtos.InsertPersonParams(); // viewModel.ToInsertPersonParams();
            //var @params = viewModel.ToInsertPersonParams();
            var cqParameters = new Test.HumanResources.Commands.InsertPersonCommandParameter(@params);
            //OnInsertPersonCommandCalling(cqParameters);
            var cqResult = await this._commandProcessor.ExecuteAsync<Test.HumanResources.Commands.InsertPersonCommandParameter, Test.HumanResources.Commands.InsertPersonCommandResult>(cqParameters);
            //OnInsertPersonCommandCalled(cqParameters, cqResult);
        }
        
        public void BackButton_OnClick()
        {
            this._navigationManager.NavigateTo("/HumanResources/PersonList");
        }
        
        public PersonDetailsComponent()
        {
        }
    }
}
