#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Hr.Commands
{
    using Library.Cqrs.Models.Commands;
    using Library.Cqrs.Models.Queries;
    
    
    /// <summary>
    /// The handler of InsertPersonCommand
    /// </summary>
    public sealed partial class InsertPersonCommandHandler : ICommandHandler<InsertPersonCommandParameter, InsertPersonCommandResult>
    {
        
    public ICommandProcessor CommandProcessor
    {
        get;
        
    }
        
    public IQueryProcessor QueryProcessor
    {
        get;
        
    }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="InsertPersonCommandHandler"/> class.
        /// </summary>
        public InsertPersonCommandHandler(ICommandProcessor commandProcessor, IQueryProcessor queryProcessor)
        {
            this.CommandProcessor = commandProcessor;
            this.QueryProcessor = queryProcessor;
        }
    }
}
#endregion
