#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Hr.Queries
{
    using HanyCo.Infra.Cqrs;
    using Test.Hr.Dtos;
    
    
    /// <summary>
    /// The result of GetAllPersons
    /// </summary>
    public sealed partial class GetAllPersonsResult : IQueryResult<GetAllPersonResult>
    {
        
    public GetAllPersonResult Result
    {
        get;
        
    }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAllPersonsResult"/> class.
        /// </summary>
        public GetAllPersonsResult(GetAllPersonResult result)
        {
            this.Result = result;
        }
    }
}
#endregion
