#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Hr.Queries
{
    using HanyCo.Infra.Cqrs;
    using Test.Hr.Dtos;
    
    
    /// <summary>
    /// The parameter of GetAllPersons
    /// </summary>
    public sealed partial class GetAllPersonsParameter : IQueryParameter<GetAllPersonsResult>
    {
        
    public GetAllPersonParams Params
    {
        get;
        
    }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAllPersonsParameter"/> class.
        /// </summary>
        public GetAllPersonsParameter(GetAllPersonParams @params)
        {
            this.Params = @params;
        }
    }
}
#endregion
