//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Queries.HumanResources.Test
{
    using Library.Cqrs.Models.Queries;
    using Library.Cqrs.Models.Commands;


    /// <summary>
    /// The handler of GetByIdPersonQuery
    /// </summary>
    public sealed partial class GetByIdPersonQueryHandler : IQueryHandler<GetByIdPersonQueryParameter, GetByIdPersonQueryResult>
    {

        /// <summary>
        /// Initializes a new instance of the <see cref="GetByIdPersonQueryHandler"/> class.
        /// </summary>
        public GetByIdPersonQueryHandler(ICommandProcessor commandProcessor, IQueryProcessor queryProcessor)
        {
            this.CommandProcessor = commandProcessor;
            this.QueryProcessor = queryProcessor;
        }

        public ICommandProcessor CommandProcessor
        {
            get;

        }

        public IQueryProcessor QueryProcessor
        {
            get;

        }
    }
}
