#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Hr.Dtos
{
    using System;
    using HanyCo.Infra.Markers;
    
    
    /// <summary>
    /// The data transfer object of DeletePersonResult
    /// </summary>
    public sealed partial class DeletePersonResult : IDto
    {
    }
}
#endregion
