//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Hr.Commands
{
    using Library.Cqrs.Models.Commands;
    using Test.Hr.Dtos;
    using HanyCo.Infra.Security.Markers;
    
    
    /// <summary>
    /// The parameter of UpdatePersonCommand
    /// </summary>
    [SecurityDescriptorAttribute(Key="UpdatePersonCommand")]
    public sealed partial class UpdatePersonCommandParameter : ICommand
    {
        
    public UpdatePersonParams Params
    {
        get;
        
    }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePersonCommandParameter"/> class.
        /// </summary>
        public UpdatePersonCommandParameter(UpdatePersonParams @params)
        {
            this.Params = @params;
        }
    }
}
