//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Commands.HumanResources.Test
{
    using Library.Cqrs.Models.Commands;
    using Library.Cqrs.Models.Queries;
    
    
    /// <summary>
    /// The handler of UpdatePersonCommand
    /// </summary>
    public sealed partial class UpdatePersonCommandHandler : ICommandHandler<UpdatePersonCommandParameter, UpdatePersonCommandResult>
    {
        
    public ICommandProcessor CommandProcessor
    {
        get;
        
    }
        
    public IQueryProcessor QueryProcessor
    {
        get;
        
    }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdatePersonCommandHandler"/> class.
        /// </summary>
        public UpdatePersonCommandHandler(ICommandProcessor commandProcessor, IQueryProcessor queryProcessor)
        {
            this.CommandProcessor = commandProcessor;
            this.QueryProcessor = queryProcessor;
        }
    }
}
