//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResources.Test.Pages
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;
    using Library.DesignPatterns.Behavioral.Observation;
    using Microsoft.Extensions.Caching.Memory;
    
    
    public sealed partial class PersonDetailsPage
    {
        
        protected override async Task OnInitializedAsync()
        {
            
            // Call developer's method.
            await this.OnLoadAsync();
        }
        
        public PersonDetailsPage()
        {
        }
    }
}
