using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text;

using HanyCo.Infra.CodeGen.Contracts.CodeGen.ViewModels;
using HanyCo.Infra.Internals.Data.DataSources;

using Library.CodeGeneration;
using Library.Data.SqlServer;
using Library.Helpers.CodeGen;
using Library.Results;

using Library.Validations;

using Services.Helpers;

namespace Services;

internal partial class FunctionalityService
{
    private sealed class CreationData(FunctionalityViewModel result, string sourceDtoName, CancellationTokenSource tokenSource)
    {
        internal readonly string COMMENT = "Auto-generated by Functionality Service.";
        private Result<FunctionalityViewModel>? _result;

        [NotNull]
        internal CancellationTokenSource CancellationTokenSource { get; } = tokenSource.ArgumentNotNull();

        [NotNull]
        internal Result<FunctionalityViewModel> Result => this._result ??= new(this.ViewModel);

        internal string SourceDtoName { get; } = sourceDtoName ?? result.SourceDto.Name!;

        internal TypePath SourceDtoType => this.ViewModel.SourceDto.GetSourceDtoType();

        [NotNull]
        internal FunctionalityViewModel ViewModel { get; } = result.ArgumentNotNull();
    }
}