//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Hr.Queries
{
    using HanyCo.Infra.Cqrs;
    using Test.Hr.Dtos;
    using HanyCo.Infra.Security.Markers;
    
    
    /// <summary>
    /// The parameter of GetAllPeopleQuery
    /// </summary>
    [SecurityDescriptorAttribute(Key="GetAllPeopleQuery")]
    public sealed partial class GetAllPeopleQueryParameter : IQueryParameter<GetAllPeopleQueryResult>
    {
        
    public GetAllPeopleParams Params
    {
        get;
        
    }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAllPeopleQueryParameter"/> class.
        /// </summary>
        public GetAllPeopleQueryParameter(GetAllPeopleParams @params)
        {
            this.Params = @params;
        }
    }
}
