//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Hr.Commands
{
    using Library.Cqrs.Models.Commands;
    using Test.Hr.Dtos;
    
    
    /// <summary>
    /// The parameter of InsertPersonCommand
    /// </summary>
    public sealed partial class InsertPersonCommandParameter : ICommand
    {
        
    public InsertPersonParams Params
    {
        get;
        
    }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="InsertPersonCommandParameter"/> class.
        /// </summary>
        public InsertPersonCommandParameter(InsertPersonParams @params)
        {
            this.Params = @params;
        }
    }
}
