#nullable enable
#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanyCo.Infra.Security.Users
{
    using HanyCo.Infra.Cqrs.Command;
    using HanyCo.Infra.Dto;
    using HanyCo.Infra.Core.Identity.Entities;
    using HanyCo.Infra.Mapping;
    
    
    /// <summary>
    /// The parameter of LoginCommand
    /// </summary>
    public sealed partial class LoginCommandParameter : ICommandParameter
    {
        
        public LoginDto Dto { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginCommandParameter"/> class.
        /// </summary>
        public LoginCommandParameter(LoginDto dto)
        {
            this.Dto = dto;
        }
    }
    
    /// <summary>
    /// The result of LoginCommand
    /// </summary>
    public sealed partial class LoginCommandResult : ICommandResult
    {
        
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginCommandResult"/> class.
        /// </summary>
        public LoginCommandResult()
        {
        }
    }
    
    /// <summary>
    /// The handler of LoginCommand
    /// </summary>
    public sealed partial class LoginCommandHandler : ICommandHandler<LoginCommandParameter,  LoginCommandResult>
    {
        
        public IInfraUserManager UserManager { get; }
        
        public IMapper Mapper { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginCommandHandler"/> class.
        /// </summary>
        public LoginCommandHandler(IInfraUserManager userManager, IMapper mapper)
        {
            this.UserManager = userManager;
            this.Mapper = mapper;
        }
    }
}
namespace HanyCo.Infra.Dto
{
    using System;
    
    
    /// <summary>
    /// The data transfer object of Login
    /// </summary>
    public sealed partial class LoginDto
    {
        
        public String UserName { get; set; }
        
        public String Password { get; set; }
    }
}
#endregion
