#nullable enable
#region Created by HanyCo Infrastructure Code Generator with ♥
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HanyCo.Infra.Security.Users
{
    using HanyCo.Infra.Cqrs.Command;
    using HanyCo.Infra.Dto;
    using System;
    using HanyCo.Infra.Core.Identity.Entities;
    using HanyCo.Infra.Mapping;
    
    
    /// <summary>
    /// The parameter of RegisterUserCommand
    /// </summary>
    public sealed partial class RegisterUserCommandParameter : ICommandParameter
    {
        
        public RegisterUserDto Dto { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterUserCommandParameter"/> class.
        /// </summary>
        public RegisterUserCommandParameter(RegisterUserDto dto)
        {
            this.Dto = dto;
        }
    }
    
    /// <summary>
    /// The result of RegisterUserCommand
    /// </summary>
    public sealed partial class RegisterUserCommandResult : ICommandResult
    {
        
        public Guid Result { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterUserCommandResult"/> class.
        /// </summary>
        public RegisterUserCommandResult(Guid result)
        {
            this.Result = result;
        }
    }
    
    /// <summary>
    /// The handler of RegisterUserCommand
    /// </summary>
    public sealed partial class RegisterUserCommandHandler : ICommandHandler<RegisterUserCommandParameter,  RegisterUserCommandResult>
    {
        
        public IInfraUserManager UserManager { get; }
        
        public IMapper Mapper { get; }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="RegisterUserCommandHandler"/> class.
        /// </summary>
        public RegisterUserCommandHandler(IInfraUserManager userManager, IMapper mapper)
        {
            this.UserManager = userManager;
            this.Mapper = mapper;
        }
    }
}
namespace HanyCo.Infra.Dto
{
    using System;
    
    
    /// <summary>
    /// The data transfer object of RegisterUser
    /// </summary>
    public sealed partial class RegisterUserDto
    {
        
        public String UserName { get; set; }
        
        public String Password { get; set; }
        
        public String FirstName { get; set; }
        
        public String LastName { get; set; }
        
        public String PhoneNumber { get; set; }
        
        public String Email { get; set; }
    }
}
#endregion
